import { withPageAuthRequired } from '@auth0/nextjs-auth0'
import type { NextPage } from 'next'
import { AppProps } from 'next/app'
import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

interface User {
  name: string
}

interface Props extends AppProps {
  user: User
}

const Index: NextPage<Props> = ({ user }) => {
  return (
    <>
      <Head>
        <title>Next Auth0 SSR App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <p>
          Welcome {user.name}!{' '}
          <Link href='/api/auth/logout'>
            <a>Logout</a>
          </Link>
        </p>
      </div>
    </>
  )
}

export const getServerSideProps = withPageAuthRequired()

export default Index
