import { withPageAuthRequired } from '@auth0/nextjs-auth0'
import { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import useSwr from 'swr'
import { createSupabaseClient } from '@/external/supabase'
import { ToDo, TODO_TABLE_NAME } from '@/libs/models/todo'
import { ResponseData } from '@/pages/api/auth/accessToken'

const fetcher = async (url: string): Promise<ResponseData | null> => {
  const response = await fetch(url)
  return response.json()
}

const ToDoPage: NextPage = () => {
  const [todos, setToDos] = useState<ToDo[]>()
  const getTodos = async (accessToken: string) => {
    const supabase = createSupabaseClient(accessToken)
    const { data } = await supabase.from<ToDo>(TODO_TABLE_NAME).select('*')
    if (data) {
      setToDos(data)
    }
  }

  const { data, error } = useSwr('/api/auth/accessToken', fetcher)
  useEffect(() => {
    if (data) {
      getTodos(data.accessToken)
    }
  }, [data])

  if (error) {
    return <div>Failed to load users</div>
  }
  if (!data || !todos) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>Next Auth0 SSR App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <ul>
          {todos.map((todo, key) => (
            <li key={key}>{todo.content}</li>
          ))}
        </ul>
      </div>
    </>
  )
}

export const getServerSideProps = withPageAuthRequired()

export default ToDoPage
